/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DLL.BookDLL;
import DLL.CategoryDLL;
import DLL.PublishDLL;
import Entity.Books;
import Entity.Categories;
import Entity.PublishingHouses;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Properties;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author PY
 */
public class BooksForm extends javax.swing.JFrame {

    /**
     * Creates new form BooksForm
     */
    BookDLL bookDll = new BookDLL();
    ArrayList<Books> listBook = new ArrayList();
    CategoryDLL cateDLL = new CategoryDLL();
    ArrayList<Categories> listCate = new ArrayList<>();
    ArrayList<PublishingHouses> listPub =  new ArrayList<>();
    PublishDLL pubDll = new PublishDLL();
    
    String filename = null;
    byte[] book_img = null;
    DefaultTableModel dtt = new DefaultTableModel();
    public BooksForm() {
        initComponents();
        this.setTitle("Book Management");
        this.setLocationRelativeTo(null);
        jPanelEditData.setVisible(false);
        jpanelSearch.setVisible(false);
        tableShow();
        categoriesShow();
        publishShow();
        chooseImg.setEnabled(false);
        jTextField2.setVisible(false);
        jButton1.setVisible(false);
        jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void tableShow(){
        Vector clums = new Vector();
        Vector data = new Vector();
        listBook = bookDll.getALL();
        clums.add("BookCode");
        clums.add("BookName");
        clums.add("Author");
        clums.add("Category");
        clums.add("PublishingHouse");
        clums.add("YearPublic");
        clums.add("Status");
        for(Books b : listBook){
            Vector row = new Vector();
            row.add(b.getBookCode().trim());
            row.add(b.getBookName().trim());
            row.add(b.getAuthor().trim());
            listCate = cateDLL.getByCode(b.getCategoryCode());
            if(listCate.size()>0){
                row.add(listCate.get(0).getCategoryName().trim());
            }
            else{
                row.add("Empty");
            }
            listPub = pubDll.getByCode(b.getPublisherCode());
            if(listPub.size()>0){
                row.add(listPub.get(0).getPubName().trim());
            }else{
                row.add("Empty");
            }     
            row.add(b.getPubYear().trim());
            row.add(b.getStus().trim());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, clums);
        jTable1.setModel(dtm);
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.requestFocus();
    }
    public void categoriesShow(){
        listCate = cateDLL.getAll();
        for (Categories c : listCate) {
            cateBox.addItem(c.getCategoryName().trim());
        }
    }
    public void publishShow(){
        listPub = pubDll.getAll();
        for (PublishingHouses p : listPub) {
            publishBox.addItem(p.getPubName().trim());
        }
    }
    
    private void displayShow(){
            if(jTable1.getSelectedRow() != -1){
                int row = jTable1.getSelectedRow();
                txtBookCode.setEditable(false);
                listBook = bookDll.getALL();
                txtBookCode.setText(listBook.get(row).getBookCode().trim());
                txtBookName.setText(listBook.get(row).getBookName());
                txtAuthor.setText(listBook.get(row).getAuthor());
                txtPubYear.setText(listBook.get(row).getPubYear());
                txtStus.setText(listBook.get(row).getStus());

                listCate = cateDLL.getByCode(listBook.get(row).getCategoryCode());
                if(listCate.size() > 0){
                    cateBox.setSelectedItem(listCate.get(0).getCategoryName());
                }else{
                    cateBox.setSelectedIndex(0);
                }

                listPub = pubDll.getByCode(listBook.get(0).getPublisherCode());
                if(listPub.size() >0){
                    publishBox.setSelectedItem(listPub.get(0).getPubName());
                }else{
                    publishBox.setSelectedIndex(0);
                }
                if(listBook.get(row).getPicture()!=null){
                    try {
                        byte[] img =  (listBook.get(row).getPicture());
                        ImageIcon imgIcon =  new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(jBookAvatar.getWidth(), jBookAvatar.getHeight(),Image.SCALE_SMOOTH));
                        jBookAvatar.setIcon(imgIcon);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, e);
                    }
                }else{
                    jBookAvatar.setIcon(null);
                }
            }
    }
    private void setAllNew(){
        txtBookCode.setEditable(true);
        txtBookCode.setText("");
        txtBookCode.requestFocus();
        txtBookName.setText("");
        txtAuthor.setText("");
        txtPubYear.setText("");
        txtStus.setText("");
        cateBox.setSelectedIndex(0);
        publishBox.setSelectedIndex(0);
        jBookAvatar.setIcon(null);
    }
    public void saveTable()throws Exception{
        BufferedWriter bfw = new BufferedWriter(new FileWriter(jTextField2.getText()));
        for(int i = 0 ; i < jTable1.getColumnCount() ; i++)
        {
          bfw.write(jTable1.getColumnName(i));
          bfw.write("\t");
        }

        for (int i = 0 ; i < jTable1.getRowCount(); i++)
        {
          bfw.newLine();
          for(int j = 0 ; j < jTable1.getColumnCount();j++)
          {
            bfw.write((String)(jTable1.getValueAt(i,j)));
            bfw.write("\t");;
          }
        }
        bfw.close();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelEditData = new javax.swing.JPanel();
        jBookBtnNew = new javax.swing.JButton();
        jBookBtnAdd = new javax.swing.JButton();
        jBookBtnUpdate = new javax.swing.JButton();
        jBookBtnRemove = new javax.swing.JButton();
        jBookBtnSaveToFile = new javax.swing.JButton();
        jBtnClose = new javax.swing.JButton();
        jPanelDataBinding = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBookCode = new javax.swing.JTextField();
        txtBookName = new javax.swing.JTextField();
        txtAuthor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPubYear = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtStus = new javax.swing.JTextField();
        jBookAvatar = new javax.swing.JLabel();
        publishBox = new javax.swing.JComboBox();
        cateBox = new javax.swing.JComboBox<>();
        chooseImg = new javax.swing.JButton();
        jpanelSearch = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        book_user = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jItemEditData = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/book1.png"))); // NOI18N
        jLabel1.setText("BOOK MANAGEMENT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanelEditData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Edit Data"));
        jPanelEditData.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jBookBtnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new.png"))); // NOI18N
        jBookBtnNew.setText("NEW");
        jBookBtnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookBtnNewActionPerformed(evt);
            }
        });
        jPanelEditData.add(jBookBtnNew);

        jBookBtnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        jBookBtnAdd.setText("ADD");
        jBookBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookBtnAddActionPerformed(evt);
            }
        });
        jPanelEditData.add(jBookBtnAdd);

        jBookBtnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        jBookBtnUpdate.setText("UPDATE");
        jBookBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookBtnUpdateActionPerformed(evt);
            }
        });
        jPanelEditData.add(jBookBtnUpdate);

        jBookBtnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/remove.png"))); // NOI18N
        jBookBtnRemove.setText("REMOVE");
        jBookBtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookBtnRemoveActionPerformed(evt);
            }
        });
        jPanelEditData.add(jBookBtnRemove);

        jBookBtnSaveToFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/save.png"))); // NOI18N
        jBookBtnSaveToFile.setText("SAVE TXT");
        jBookBtnSaveToFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookBtnSaveToFileActionPerformed(evt);
            }
        });
        jPanelEditData.add(jBookBtnSaveToFile);

        jBtnClose.setForeground(new java.awt.Color(255, 0, 0));
        jBtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close.png"))); // NOI18N
        jBtnClose.setText("CLOSE");
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });
        jPanelEditData.add(jBtnClose);

        jPanelDataBinding.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Data Binding"));

        jLabel2.setText("Book Code :");

        jLabel3.setText("Book Name :");

        jLabel4.setText("Author :");

        jLabel5.setText("Category :");

        jLabel6.setText("Publishing House :");

        jLabel7.setText("Publishing Year :");

        jLabel8.setText("Status :");

        jBookAvatar.setBackground(new java.awt.Color(0, 0, 0));

        chooseImg.setText("Choose");
        chooseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDataBindingLayout = new javax.swing.GroupLayout(jPanelDataBinding);
        jPanelDataBinding.setLayout(jPanelDataBindingLayout);
        jPanelDataBindingLayout.setHorizontalGroup(
            jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataBindingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAuthor)
                    .addComponent(txtBookName)
                    .addComponent(publishBox, 0, 120, Short.MAX_VALUE)
                    .addComponent(cateBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDataBindingLayout.createSequentialGroup()
                        .addComponent(chooseImg)
                        .addGap(18, 18, 18)
                        .addComponent(jBookAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDataBindingLayout.createSequentialGroup()
                        .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPubYear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        jPanelDataBindingLayout.setVerticalGroup(
            jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDataBindingLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPubYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtStus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDataBindingLayout.createSequentialGroup()
                        .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cateBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseImg))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDataBindingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(publishBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBookAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelSearchLayout = new javax.swing.GroupLayout(jpanelSearch);
        jpanelSearch.setLayout(jpanelSearchLayout);
        jpanelSearchLayout.setHorizontalGroup(
            jpanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelSearchLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jpanelSearchLayout.setVerticalGroup(
            jpanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel9.setText("Hello :");

        book_user.setText("jLabel10");

        jTextField2.setText("D://book1.txt");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("System");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/em2.png"))); // NOI18N
        jMenuItem1.setText("Employees Management");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pub1.png"))); // NOI18N
        jMenuItem2.setText("PublishingHouse Management");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/card2.png"))); // NOI18N
        jMenuItem3.setText("ReaderCards Management");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reader2.png"))); // NOI18N
        jMenuItem4.setText("Readers Managements");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/return2.png"))); // NOI18N
        jMenuItem5.setText("ReturnExchange Management");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Function");

        jItemEditData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/edit.png"))); // NOI18N
        jItemEditData.setText("Edit Data");
        jItemEditData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemEditDataActionPerformed(evt);
            }
        });
        jMenu2.add(jItemEditData);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        jMenuItem6.setText("Search");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem8.setText("Find By Code");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Back");

        jMenuItem7.setText("Back to Login");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEditData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDataBinding, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addComponent(book_user)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(book_user)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDataBinding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelEditData, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemEditDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemEditDataActionPerformed
        jPanelEditData.setVisible(true);
        chooseImg.setEnabled(true);
    }//GEN-LAST:event_jItemEditDataActionPerformed

    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        jPanelEditData.setVisible(false);
        chooseImg.setEnabled(false);
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        displayShow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBookBtnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookBtnNewActionPerformed
        setAllNew();
    }//GEN-LAST:event_jBookBtnNewActionPerformed

    private void jBookBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookBtnAddActionPerformed
        if(bookDll.countCode(txtBookCode.getText().trim()) == 0){    
            listCate = cateDLL.getAll();
            listPub = pubDll.getAll();
            String bookCode = txtBookCode.getText().trim();
            String bookName = txtBookName.getText().trim();
            String author = txtAuthor.getText().trim();
            String year = txtPubYear.getText().trim();
            String s = txtStus.getText().trim();
            int rowCate = cateBox.getSelectedIndex();
            int rowPub = publishBox.getSelectedIndex();
            String cate = listCate.get(rowCate).getCategoryCode();
            String pub = listPub.get(rowPub).getPubCode();

            Books bk = new Books();
            bk.setBookCode(bookCode);
            bk.setBookName(bookName);
            bk.setAuthor(author);
            bk.setPubYear(year);
            bk.setStus(s);
            bk.setPublisherCode(pub);
            bk.setCategoryCode(cate);
            bk.setPicture(book_img);
            if(bookDll.AddData(bk)){
                JOptionPane.showMessageDialog(this, "Added!");
                System.out.println("Added Book Name : "+bookName);
                tableShow();
            }else{
                JOptionPane.showMessageDialog(this, "Add Failed!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "BookCode: "+ txtBookCode.getText().trim() +" has already exist!");
        }
    }//GEN-LAST:event_jBookBtnAddActionPerformed

    private void jBookBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookBtnUpdateActionPerformed
        if(jTable1.getSelectedRow()!=-1){
            listCate = cateDLL.getAll();
            listPub = pubDll.getAll();
            String bookCode = txtBookCode.getText().trim();
            String bookName = txtBookName.getText().trim();
            String author = txtAuthor.getText().trim();
            String year = txtPubYear.getText().trim();
            String s = txtStus.getText().trim();
            int rowCate = cateBox.getSelectedIndex();
            int rowPub = publishBox.getSelectedIndex();
            String cate = listCate.get(rowCate).getCategoryCode();
            String pub = listPub.get(rowPub).getPubCode();

            Books bk = new Books();
            bk.setBookCode(bookCode);
            bk.setBookName(bookName);
            bk.setAuthor(author);
            bk.setPubYear(year);
            bk.setStus(s);
            bk.setPublisherCode(pub);
            bk.setCategoryCode(cate);
            bk.setPicture(book_img);

            if(bookDll.updateData(bk)){
                JOptionPane.showMessageDialog(this, "Updated!");
                tableShow();
                System.out.println("Update Book Name : "+bookName);
            }else{
                JOptionPane.showMessageDialog(this, "Update Failed!");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Choose a book!");
        }
    }//GEN-LAST:event_jBookBtnUpdateActionPerformed

    private void jBookBtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookBtnRemoveActionPerformed
        if(jTable1.getSelectedRow()!=-1){
            if(JOptionPane.showConfirmDialog(this, "Delete this book? (Y/N)")==JOptionPane.OK_OPTION){
                if(bookDll.removeData(txtBookCode.getText())){
                    JOptionPane.showMessageDialog(this, "Deleted!");
                    tableShow();
                    System.out.println("Deleted BookName: "+ txtBookName.getText());
                }else{
                    JOptionPane.showMessageDialog(this, "Detete Failed!");
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Choose a book!");
        }
    }//GEN-LAST:event_jBookBtnRemoveActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EmployeesForm e = new EmployeesForm();
        e.setVisible(true);
        e.emuser.setText(book_user.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PublishForm p = new PublishForm();
        p.setVisible(true);
        p.pubuser.setText(book_user.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ReCardsForm r = new ReCardsForm();
        r.setVisible(true);
        r.carduser.setText(book_user.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ReadersForm r = new ReadersForm();
        r.setVisible(true);
        r.reuser.setText(book_user.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ReturnExchangeForm r = new ReturnExchangeForm();
        r.setVisible(true);
        r.reexuser.setText(book_user.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void chooseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImgActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename =  f.getAbsolutePath();
        ImageIcon img =  new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jBookAvatar.getWidth(), jBookAvatar.getHeight(),Image.SCALE_SMOOTH));
        jBookAvatar.setIcon(img);
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos =  new ByteArrayOutputStream();
            byte[] buf = new  byte[1024];
            for(int readNum;(readNum=fis.read(buf))!=-1;){
                bos.write(buf,0,readNum);
                
            }
            book_img=bos.toByteArray();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_chooseImgActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        jpanelSearch.setVisible(true);
        dtt = (DefaultTableModel)jTable1.getModel();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
        String s = jTextField1.getText().trim();
        TableRowSorter<DefaultTableModel> tr =  new TableRowSorter<DefaultTableModel>(tm);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(s));
                
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField1.requestFocus();
        jpanelSearch.setVisible(false);
        tableShow();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        LoginForm l = new LoginForm();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jBookBtnSaveToFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBookBtnSaveToFileActionPerformed
        jButton1.setVisible(true);
        jButton3.setVisible(true);
        jTextField2.setVisible(true);
    }//GEN-LAST:event_jBookBtnSaveToFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                saveTable();
                JOptionPane.showMessageDialog(this, "Data has saved to "+ jTextField2.getText());
                
            } catch (Exception ex) {
                Logger.getLogger(BooksForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextField2.setVisible(false);
        jButton3.setVisible(false);
        jButton1.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FindByCodeProcedure f = new FindByCodeProcedure();
        f.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooksForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BooksForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel book_user;
    private javax.swing.JComboBox<String> cateBox;
    private javax.swing.JButton chooseImg;
    private javax.swing.JLabel jBookAvatar;
    private javax.swing.JButton jBookBtnAdd;
    private javax.swing.JButton jBookBtnNew;
    private javax.swing.JButton jBookBtnRemove;
    private javax.swing.JButton jBookBtnSaveToFile;
    private javax.swing.JButton jBookBtnUpdate;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenuItem jItemEditData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanelDataBinding;
    private javax.swing.JPanel jPanelEditData;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel jpanelSearch;
    private javax.swing.JComboBox publishBox;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtBookCode;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtPubYear;
    private javax.swing.JTextField txtStus;
    // End of variables declaration//GEN-END:variables
}
