/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAL.DatabaseAccess;
import DLL.ProfileDLL;
import DLL.ProfileUserDLL;
import DLL.RoleDLL;
import Entity.Profile;
import Entity.ProfileUsers;
import Entity.Role;
import Entity.UserDetails;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;
import oracle.jdbc.OracleConnection;
import oracle.jdbc.pool.OracleDataSource;

/**
 *
 * @author PY
 */
public class user extends javax.swing.JFrame {

    /**
     * Creates new form user
     */
    ArrayList<Profile> listProfile = new ArrayList<>();
    ProfileDLL proDLL = new ProfileDLL();
    
    ArrayList<ProfileUsers> listProU= new ArrayList<>();
    ProfileUserDLL proUDLL = new ProfileUserDLL();
    
    ArrayList<UserDetails> listUd= new ArrayList<>();
    ProfileUserDLL uDeDLL = new ProfileUserDLL();
    
    ArrayList<Profile> listTableS = new ArrayList<>();
    ProfileDLL tableDLL = new ProfileDLL();
    
    ArrayList<Role> listRole = new ArrayList<>();
    RoleDLL roleDLL = new RoleDLL();
    public user() {
        initComponents();
        this.setTitle("Profiles And Users");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        try {
            treeCustom();
            tableSpaceShow();
            proFileShow();
            roleShow();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    private void roleShow(){
        comboRole.addItem("<None>");
        listRole = roleDLL.getRole();
        listRole.forEach((r) ->{
            comboRole.addItem(r.getName());
        });
    }
    private void proFileShow(){
        listProfile = proDLL.getALL();
        listProfile.forEach((p) -> {
            jProfileList.addItem(p.getName());
        });
    }
    private void tableSpaceShow(){
        listTableS = tableDLL.getTablespace();
        for(Profile p : listTableS){
            jTableSpaceList.addItem(p.getName());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        user = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        tables = new javax.swing.JTextField();
        created = new javax.swing.JTextField();
        profile = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jTableSpaceList = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        quota = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jProfileList = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        rolename = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        boxSelect = new javax.swing.JCheckBox();
        boxInsert = new javax.swing.JCheckBox();
        boxUpdate = new javax.swing.JCheckBox();
        boxDelete = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        comboTable = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        pass.setText("jPasswordField1");

        jButton1.setText("Create Profile");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("USERNAME");

        jLabel2.setText("PASSWORD");

        jLabel3.setText("ACCOUNT_STATUS");

        jLabel4.setText("DEFAULT_TABLESPACE");

        jLabel5.setText("CREATED");

        jLabel6.setText("PROFILE");

        jLabel7.setText("PROFILE_NAME");

        jLabel8.setText("PASSWORD_LIFE_TIME");

        jLabel9.setText("FAILED_LOGIN_ATTEMPTS");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNLIMITED", "3", "6", "10", "DEFAULT" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNLIMITED", "30", "60", "120", "180", "DEFAULT" }));

        jButton2.setText("Create User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("USERNAME");

        jLabel12.setText("PASSWORD");

        jLabel13.setText("TABLESPACE");

        jLabel14.setText("QUOTA_SIZE");

        jLabel15.setText("MB");

        jLabel16.setText("PROFILE");

        jLabel10.setText("ROLES :");

        comboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoleActionPerformed(evt);
            }
        });

        jLabel17.setText("NAME :");

        jButton3.setText("Create Role");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Grant to user");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setText("Object Privileges :");

        boxSelect.setText("SELECT");

        boxInsert.setText("INSERT");

        boxUpdate.setText("UPDATE");

        boxDelete.setText("DELETE");

        jLabel19.setText("ON TABLE :");

        comboTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOOKS", "CATEGORYS", "EMPLOYEES", "READERS", "RETURNEXCHANGE" }));

        jButton6.setText("Delete Role");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Revoke");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boxInsert)
                        .addGap(18, 18, 18)
                        .addComponent(boxDelete))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boxSelect)
                        .addGap(18, 18, 18)
                        .addComponent(boxUpdate)))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolename)
                            .addComponent(comboRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(comboTable, 0, 178, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rolename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxSelect)
                    .addComponent(boxUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxInsert)
                    .addComponent(boxDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(comboTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)))
        );

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(quota, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addGap(0, 7, Short.MAX_VALUE))
                                    .addComponent(jTableSpaceList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jProfileList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tables)
                            .addComponent(created)
                            .addComponent(profile)
                            .addComponent(user)
                            .addComponent(status)
                            .addComponent(pass))))
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton5)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(created, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTableSpaceList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jProfileList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(quota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        
        if(jTree1.getSelectionPath() == null){
            return;
        }
        DefaultMutableTreeNode userNode = (DefaultMutableTreeNode) jTree1.getSelectionPath().getLastPathComponent();
        listUd = uDeDLL.getDetails(userNode.toString());
        
        if(listUd!=null){
            for(UserDetails u : listUd) {
                user.setText(u.getUsername());
                pass.setText(u.getPass());
                created.setText(u.getCreated());
                status.setText(u.getStatus());
                profile.setText(u.getProfile());
                tables.setText(u.getTablespace());
            }
        }else{
            user.setText("");
        }
    }//GEN-LAST:event_jTree1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if("".equals(jTextField1.getText())){
            JOptionPane.showMessageDialog(this, "Type correctly!!");
        }else{
            String query = "CREATE PROFILE "+jTextField1.getText() + " LIMIT\n" +
                            "PASSWORD_LIFE_TIME "+jComboBox2.getSelectedItem().toString()+" \n" +
                            "FAILED_LOGIN_ATTEMPTS "+jComboBox1.getSelectedItem().toString();
            try {
                // connect to database
                Class.forName("oracle.jdbc.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", 
                        "sys as sysdba", "Oracle123");

                // crate statement to insert student
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.execute();
                JOptionPane.showMessageDialog(this, "Profile Created!");
                stmt.close();
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }
            treeCustom();
            proFileShow();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(username.getText().equals("") || password.getText().equals("") || quota.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Type Correctly!!");
        }else{
            String first = "alter session set \"_ORACLE_SCRIPT\"=true";
            String query = "CREATE USER "+username.getText().trim()+
                    " IDENTIFIED BY "+password.getText().trim()+" DEFAULT TABLESPACE "+jTableSpaceList.getSelectedItem().toString()+
                    " QUOTA "+quota.getText().trim()+"M"+" ON "+jTableSpaceList.getSelectedItem().toString()+" PROFILE "+jProfileList.getSelectedItem().toString()+" ACCOUNT unlock";
            try {
                // connect to database
                Class.forName("oracle.jdbc.OracleDriver");
                Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", 
                        "sys as sysdba", "Oracle123");

                // crate statement to insert student
                PreparedStatement stmtone = conn.prepareStatement(first);
                PreparedStatement stmt = conn.prepareStatement(query);
                stmtone.execute();
                stmt.execute();
                JOptionPane.showMessageDialog(this, "User Created!");
                stmt.close();
                conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            }
            treeCustom();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoleActionPerformed

    }//GEN-LAST:event_comboRoleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String q1 = "Create role " + rolename.getText();
        String t1 = "";
        String t2 = "";
        String t3 = "";
        String t4 = "";
        if(rolename.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Fill the name of a role!");
            return;
        }
        
        if(!"<None>".equals(comboRole.getSelectedItem().toString().trim())){
            if(boxSelect.isSelected()){
                t1= "SELECT";
            }
            if(boxUpdate.isSelected()){
                t2= "UPDATE";
            }
            if(boxInsert.isSelected()){
                t3= "INSERT";
            }
            if(boxDelete.isSelected()){
                t4= "DELETE";
            }
            String q2 = "GRANT " + comboRole.getSelectedItem().toString()+ " TO " + rolename.getText();
            String q3 = "GRANT "+ t1+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            String q4 = "GRANT "+ t2+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            String q5 = "GRANT "+ t3+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            String q6 = "GRANT "+ t4+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            try {
            // Set the connection properties.
            // required: SYSDBA
            Properties prop = new Properties();
            prop.setProperty("user","sys");
            prop.setProperty("password","Oracle123");
            prop.setProperty("internal_logon","sysdba");

            OracleDataSource ods = new OracleDataSource();
            ods.setConnectionProperties(prop);
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            OracleConnection ocon = (OracleConnection)ods.getConnection();
            System.out.println("Connected");     

            // shutdown the database
            Statement stmt = ocon.createStatement();
            stmt.execute(q1);
            System.out.println("Created role "+rolename.getText());
            stmt.execute(q2);
            System.out.println("GRANT "+ comboRole.getSelectedItem().toString()+ " TO " + rolename.getText() + " Successed!");
            if(boxSelect.isSelected()){
                stmt.execute(q3);
                System.out.println("Granted " + t1 +  "Successed!");
            }
            if(boxUpdate.isSelected()){
                stmt.execute(q4);
                System.out.println("Granted " + t2 +  "Successed!");
            }
            if(boxInsert.isSelected()){
                stmt.execute(q5);
                System.out.println("Granted " + t3 +  "Successed!");
            }
            if(boxDelete.isSelected()){
                stmt.execute(q6);
                System.out.println("Granted " + t4 +  "Successed!");
            }
            stmt.close();
            System.out.println("Role created");
            JOptionPane.showMessageDialog(this, "Role created!");
            ocon.close();
            ods.close();
            roleShow();

          } catch(SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e);
          }
        }
        else{
            if(boxSelect.isSelected()){
                t1= "SELECT";
            }
            if(boxUpdate.isSelected()){
                t2= "UPDATE";
            }
            if(boxInsert.isSelected()){
                t3= "INSERT";
            }
            if(boxDelete.isSelected()){
                t4= "DELETE";
            }
            String q2 = "GRANT "+ t1+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            String q3 = "GRANT "+ t2+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            String q4 = "GRANT "+ t3+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            String q5 = "GRANT "+ t4+ " ON " + comboTable.getSelectedItem().toString()+ " TO " + rolename.getText();
            try {
            // Set the connection properties.
            // required: SYSDBA
            Properties prop = new Properties();
            prop.setProperty("user","sys");
            prop.setProperty("password","Oracle123");
            prop.setProperty("internal_logon","sysdba");

            OracleDataSource ods = new OracleDataSource();
            ods.setConnectionProperties(prop);
            ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
            OracleConnection ocon = (OracleConnection)ods.getConnection();
            System.out.println("Connected");     

            // shutdown the database
            Statement stmt = ocon.createStatement();
            stmt.execute(q1);
            System.out.println("Created role "+rolename.getText());
            if(boxSelect.isSelected()){
                stmt.execute(q2);
                System.out.println("Granted " + t1 +  "Successed!");
            }
            if(boxUpdate.isSelected()){
                stmt.execute(q3);
                System.out.println("Granted " + t2 +  "Successed!");
            }
            if(boxInsert.isSelected()){
                stmt.execute(q4);
                System.out.println("Granted " + t3 +  "Successed!");
            }
            if(boxDelete.isSelected()){
                stmt.execute(q5);
                System.out.println("Granted " + t4 +  "Successed!");
            }
            
            stmt.close();
            System.out.println("Role created");
            JOptionPane.showMessageDialog(this, "Role created!");
            ocon.close();
            ods.close();
            roleShow();

          } catch(SQLException e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e);
          }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jTree1.getSelectionPath() == null){
            JOptionPane.showMessageDialog(this, "Select a user!");
            return;
        }
        if("<None>".equals(comboRole.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(this, "Select a role to grant!");
            return;
        }
            TreeNode selected = (TreeNode) jTree1.getSelectionPath().getLastPathComponent();
            if(selected.isLeaf() && (selected.getParent() != jTree1.getModel().getRoot())){
                String role  = comboRole.getSelectedItem().toString().trim();
                String query = "GRANT " + role + " TO " + selected.toString().trim();
                try {
                // Set the connection properties.
                // required: SYSDBA
                Properties prop = new Properties();
                prop.setProperty("user","sys");
                prop.setProperty("password","Oracle123");
                prop.setProperty("internal_logon","sysdba");

                OracleDataSource ods = new OracleDataSource();
                ods.setConnectionProperties(prop);
                ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                OracleConnection ocon = (OracleConnection)ods.getConnection();
                System.out.println("Connected");     

                // shutdown the database
                Statement stmt = ocon.createStatement();
                stmt.execute(query);
                stmt.close();
                System.out.println("Granted role "+ rolename.getText() + " TO " + selected.toString() + " Successfully!");
                JOptionPane.showMessageDialog(this, "Granted role "+ rolename.getText() + " TO " + selected.toString() + " Successfully!");
                ocon.close();
                ods.close();
                roleShow();

              } catch(SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
              }
            }else{
                JOptionPane.showMessageDialog(this, "Select a user not a Profile!");
            }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Delete this role?")==JOptionPane.OK_OPTION){
            String selected = comboRole.getSelectedItem().toString().trim();
        
        
        if("<None>".equals(selected)){
            JOptionPane.showMessageDialog(this, "Choose a role");
            return;
        }
        
        listRole = roleDLL.getbyName(selected);
        
        if(listRole.isEmpty()){
            JOptionPane.showMessageDialog(this, "Can't delete common role!");
            return;
        }
        String query = "Drop role " + selected;
        try {
                // Set the connection properties.
                // required: SYSDBA
                Properties prop = new Properties();
                prop.setProperty("user","sys");
                prop.setProperty("password","Oracle123");
                prop.setProperty("internal_logon","sysdba");

                OracleDataSource ods = new OracleDataSource();
                ods.setConnectionProperties(prop);
                ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                OracleConnection ocon = (OracleConnection)ods.getConnection();
                System.out.println("Connected");     

                // shutdown the database
                Statement stmt = ocon.createStatement();
                stmt.execute(query);
                stmt.close();
                System.out.println("Delete role " + selected + " Successfully!");
                JOptionPane.showMessageDialog(this, "Delete role " + selected + " Successfully!");
                ocon.close();
                ods.close();
                comboRole.setSelectedIndex(0);
                roleShow();

              } catch(SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
              }
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTree1.getSelectionPath() == null){
            JOptionPane.showMessageDialog(this, "Select a user or profile to delete!");
            return;
        }
        TreeNode selected = (TreeNode)jTree1.getSelectionPath().getLastPathComponent();
        if(selected.isLeaf() && selected.getParent() != jTree1.getModel().getRoot()){
            String query = "DROP USER "+ selected.toString().trim() +" CASCADE";
            try {
                // Set the connection properties.
                // required: SYSDBA
                Properties prop = new Properties();
                prop.setProperty("user","sys");
                prop.setProperty("password","Oracle123");
                prop.setProperty("internal_logon","sysdba");

                OracleDataSource ods = new OracleDataSource();
                ods.setConnectionProperties(prop);
                ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                OracleConnection ocon = (OracleConnection)ods.getConnection();
                System.out.println("Connected");     

                // shutdown the database
                Statement stmt = ocon.createStatement();
                stmt.execute(query);
                stmt.close();
                System.out.println("Delete user " + selected + " Successfully!");
                JOptionPane.showMessageDialog(this, "Delete user " + selected + " Successfully!");
                ocon.close();
                ods.close();
                treeCustom();
              } catch(SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
              }
            return;
        }
        if(selected.getParent() == jTree1.getModel().getRoot()){
            String query = "DROP PROFILE "+ selected + " CASCADE";
            if(JOptionPane.showConfirmDialog(this, "Delete this profile? ( All users inside it will change to DEFAULT profile )")==JOptionPane.OK_OPTION){
                try {
                // Set the connection properties.
                // required: SYSDBA
                Properties prop = new Properties();
                prop.setProperty("user","sys");
                prop.setProperty("password","Oracle123");
                prop.setProperty("internal_logon","sysdba");

                OracleDataSource ods = new OracleDataSource();
                ods.setConnectionProperties(prop);
                ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                OracleConnection ocon = (OracleConnection)ods.getConnection();
                System.out.println("Connected");     

                // shutdown the database
                Statement stmt = ocon.createStatement();
                stmt.execute(query);
                stmt.close();
                System.out.println("Delete profile " + selected + " Successfully!");
                JOptionPane.showMessageDialog(this, "Delete profile " + selected + " Successfully!");
                ocon.close();
                ods.close();
                treeCustom();
              } catch(SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
              }
            }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String selected = comboRole.getSelectedItem().toString();
        
        
        if(jTree1.getSelectionPath() == null){
            return;
        }
        if(selected.equals("<None>")){
            JOptionPane.showMessageDialog(this, "Choose a roles to revoke!");
            return;
        }
        TreeNode userNode = (TreeNode)jTree1.getSelectionPath().getLastPathComponent();
        if(userNode.isLeaf() && userNode.getParent() != jTree1.getModel().getRoot()){
            
            String query = "REVOKE "+ selected + " FROM " + userNode.toString();
            try {
                // Set the connection properties.
                // required: SYSDBA
                Properties prop = new Properties();
                prop.setProperty("user","sys");
                prop.setProperty("password","Oracle123");
                prop.setProperty("internal_logon","sysdba");

                OracleDataSource ods = new OracleDataSource();
                ods.setConnectionProperties(prop);
                ods.setURL("jdbc:oracle:thin:@localhost:1521:orcl");
                OracleConnection ocon = (OracleConnection)ods.getConnection();
                System.out.println("Connected");     

                // shutdown the database
                Statement stmt = ocon.createStatement();
                stmt.execute(query);
                stmt.close();
                System.out.println("Revoke " + selected + " FROM " + userNode.toString() + " Successfully!");
                JOptionPane.showMessageDialog(this, "Revoke " + selected + " FROM " + userNode + " Successfully!");
                ocon.close();
                ods.close();
                treeCustom();
              } catch(SQLException e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e);
              }
        }else{
            JOptionPane.showMessageDialog(this, "Choose a user!");
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    public void treeCustom(){
        //create the root node
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Profiles And Users");
        //create the child nodes
        listProfile = proDLL.getALL();
        
        for(Profile p : listProfile){
            DefaultMutableTreeNode profileNode = new DefaultMutableTreeNode(p.getName());
            root.add(profileNode);
            listProU = proUDLL.getALL(p.getName());
            for(ProfileUsers pp : listProU){
                DefaultMutableTreeNode userNode = new DefaultMutableTreeNode(pp.getUsername());
                profileNode.add(userNode);
            }
            
        }
         
        //create the tree by passing in the root node
        DefaultTreeModel dtm = new DefaultTreeModel(root);
        jTree1.setModel(dtm);

        for (int i = 0; i < jTree1.getRowCount(); i++) {
            jTree1.expandRow(i);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxDelete;
    private javax.swing.JCheckBox boxInsert;
    private javax.swing.JCheckBox boxSelect;
    private javax.swing.JCheckBox boxUpdate;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JComboBox<String> comboTable;
    private javax.swing.JTextField created;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jProfileList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jTableSpaceList;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField profile;
    private javax.swing.JTextField quota;
    private javax.swing.JTextField rolename;
    private javax.swing.JTextField status;
    private javax.swing.JTextField tables;
    private javax.swing.JTextField user;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
